sonar.projectKey=terraform-k8s-github-actions
sonar.projectName=Terraform Kubernetes GitHub Actions
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://host.docker.internal:9000

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/.git/**,**/.terraform/**,**/__pycache__/**,**/venv/**,**/*.png,**/*.jpg